# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Default build command.
  command   = "yarn build"
  functions = "out_functions"
  publish   = "out_publish"
  # Environment variables
  environment = { YARN_VERSION = "1.22.5", NODE_VERSION = "12" }
